# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleAppMeasurement', '~> 5.2.0'
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Firestore', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'

end
